# Configuration for mkdocs-awesome-nav plugin
# This file explicitly defines the navigation order and titles

nav: 
  - Home: index.md
  - Model: model.md
  - Data: data.md
  - Setup: installation/quick_start.md
  - Configuration: configuration.md
  - Releases: releases.md
  - Tutorials: tutorials
  - Reference: reference
  # - Miscellaneous: misc.md
  - Release Guide: release-guide.md
  # - Testing: testing-release-flow.md 


